# Generated by Django 4.0.3 on 2022-03-20 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipo_erogaciones',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subfamilias',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubros',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familias',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='familia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumo.familias'),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='rubro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumo.rubros'),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='subfamilia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumo.subfamilias'),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='tipo_erogacione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumo.tipo_erogaciones'),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='unidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumo.unidades'),
        ),
        migrations.AddField(
            model_name='alta_insumos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
