# Generated by Django 4.0.3 on 2022-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta_empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion_calle', models.CharField(max_length=255)),
                ('direccion_nro', models.CharField(max_length=255)),
                ('direccion_localidad', models.CharField(max_length=255)),
                ('direccion_provincia', models.CharField(max_length=255)),
                ('direccion_pais', models.CharField(max_length=255)),
                ('direccion_cod_postal', models.CharField(max_length=255)),
                ('cuit', models.IntegerField(blank=True, null=True)),
                ('cond_IVA_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_cierre', models.DateField()),
                ('moneda_primaria_id', models.CharField(blank=True, max_length=255, null=True)),
                ('moneda_secundaria_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('empresas', models.CharField(blank=True, max_length=255, null=True)),
                ('usuarios', models.CharField(blank=True, max_length=255, null=True)),
                ('accesos_por_rol', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
