# Generated by Django 4.0.3 on 2022-03-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_initial'),
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta_empresas',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.rubros'),
        ),
    ]
