# Generated by Django 4.0.3 on 2022-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta_facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_emisor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_tarjeta', models.IntegerField(blank=True, null=True)),
                ('vto_fecha', models.DateField(blank=True, null=True)),
                ('cod_verificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
