# Generated by Django 4.0.3 on 2022-03-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta_usuarios',
            name='empresa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.alta_empresas'),
        ),
    ]
