# Generated by Django 4.0.3 on 2022-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_alta_empresas_rubro'),
        ('usuario', '0002_alter_alta_usuarios_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alta_usuarios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='alta_usuarios',
            name='empresa',
            field=models.ManyToManyField(null=True, to='empresa.alta_empresas'),
        ),
    ]
